# docker/docker-compose.yml — Swarm OK (red overlay y nombre nuevo)

services:
  anything-llm:
    image: mintplexlabs/anythingllm:latest
    cap_add:
      - SYS_ADMIN
    environment:
      - STORAGE_DIR=/app/server/storage
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - LLM_PROVIDER=${LLM_PROVIDER}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
      - OPENAI_BASE_PATH=${OPENAI_BASE_PATH}
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
    volumes:
      - anything_storage:/app/server/storage
      - collector_hotdir:/app/collector/hotdir
      - collector_outputs:/app/collector/outputs
    # Mantén esto solo si quieres probar por IP:PUERTO; con Domains no es necesario
    ports:
      - "3001:3001"
    networks:
      - anything_llm_net
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  anything_storage:
  collector_hotdir:
  collector_outputs:

networks:
  anything_llm_net:
    driver: overlay
    attachable: true
